name: Deploy on local VM
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker compose up
        run: |
          docker-compose pull
          docker-compose up -d --build
